apiVersion: v1
kind: PersistentVolume
metadata:
  name: omh
  labels:
    type: local
    app: omh
spec:
  storageClassName: manual
  hostPath:
    path: "/var/lib/rancher/k3s/storage/omh"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omh
  labels:
    app: omh
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omh
  template:
    metadata:
      labels:
        app: omh
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: web
        image: ghcp.io/sverdlovsky/core-edu-web:latest
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: series
          mountPath: /mnt
        env:
        - name: DOMAIN
          value: ####
      - name: api
        image: ghcp.io/sverdlovsky/core-edu-api:latest
        ports:
        - name: api
          containerPort: 8080
        env:
        - name: DOMAIN
          value: ####
        - name: ADMIN_EMAIL
          value: #########
        - name: DATABASE_URL
          value: postgresql://omh:omh_pass@postgres:5432/omh
        - name: JWT_SECRET
          value: ########
      - name: auth
        image: ghcp.io/sverdlovsky/core-edu-auth:latest
        ports:
        - name: auth
          containerPort: 8000
        env:
        - name: DOMAIN
          value: ####
        - name: YANDEX_CLIENT_ID
          value: ##############
        - name: YANDEX_CLIENT_SECRET
          value: ##################
        - name: GOOGLE_CLIENT_ID
          value: ##############
        - name: GOOGLE_CLIENT_SECRET
          value: ##################
        - name: GITHUB_CLIENT_ID
          value: ##############
        - name: GITHUB_CLIENT_SECRET
          value: ##################
        - name: SECRET_KEY
          value: ########
        - name: JWT_SECRET
          value: ########
      volumes:
      - name: series
        persistentVolumeClaim:
          claimName: omh
---
apiVersion: v1
kind: Service
metadata:
  name: omh
  labels:
    app: omh
spec:
  type: ClusterIP
  selector:
    app: omh
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: auth
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omh
  annotations:
    ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  tls:
  - hosts:
    - example.com
    - media.example.com
    - auth.example.com
    - api.example.com
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omh-root
            port:
              name: http

  - host: learn.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omh-learn
            port:
              name: http

  - host: media.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omh-media
            port:
              name: http

  - host: auth.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omh-auth
            port:
              name: auth

  - host: api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omh-api
            port:
              name: api

